using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;

namespace XUnitAssured.Playwright.Codegen;

/// <summary>
/// Translates Playwright C# Library code (generated by the Inspector/Codegen)
/// into the XUnitAssured fluent DSL.
/// <para>
/// <b>Usage:</b>
/// <code>
/// var playwrightCode = @"
///     await page.GetByRole(AriaRole.Button, new() { Name = ""Click me"" }).ClickAsync();
///     await page.GetByLabel(""Email"").FillAsync(""user@test.com"");
/// ";
/// var dsl = PlaywrightCodeTranslator.Translate(playwrightCode);
/// // Output:
/// //   .ClickByRole(AriaRole.Button, "Click me")
/// //   .FillByLabel("Email", "user@test.com")
/// </code>
/// </para>
/// </summary>
public static class PlaywrightCodeTranslator
{
	// ──────────────────────────────────────────────
	// Boilerplate lines to skip
	// ──────────────────────────────────────────────

	private static readonly string[] BoilerplateStartPatterns =
	[
		"using ",
		"using var playwright",
		"await using var browser",
		"var context = await browser",
		"var page = await context",
		"await browser.CloseAsync",
		"await context.CloseAsync",
		"Headless =",
		"SlowMo =",
	];

	/// <summary>
	/// Lines that are exactly these (after trim) are boilerplate.
	/// </summary>
	private static readonly HashSet<string> BoilerplateExactLines = new(StringComparer.Ordinal)
	{
		"{", "}", "};", "});", ");", "(",
	};

	// ──────────────────────────────────────────────
	// Action name mapping: Playwright async method → DSL prefix
	// ──────────────────────────────────────────────

	private static readonly Dictionary<string, string> ActionMap = new(StringComparer.OrdinalIgnoreCase)
	{
		["Click"] = "Click",
		["DblClick"] = "DoubleClick",
		["Fill"] = "Fill",
		["Clear"] = "Clear",
		["Check"] = "Check",
		["Uncheck"] = "Uncheck",
		["SelectOption"] = "SelectOption",
		["Hover"] = "Hover",
		["Focus"] = "Focus",
		["Press"] = "Press",
		["PressSequentially"] = "TypeText",
		["SetInputFiles"] = "UploadFile",
	};

	// ──────────────────────────────────────────────
	// Locator suffix mapping: GetBy* → DSL suffix
	// ──────────────────────────────────────────────

	private static readonly Dictionary<string, string> LocatorSuffixMap = new(StringComparer.OrdinalIgnoreCase)
	{
		["GetByRole"] = "ByRole",
		["GetByText"] = "ByText",
		["GetByLabel"] = "ByLabel",
		["GetByPlaceholder"] = "ByPlaceholder",
		["GetByTestId"] = "ByTestId",
		["GetByTitle"] = "ByTitle",
		["Locator"] = "",
	};

	// ──────────────────────────────────────────────
	// Master regex patterns
	// ──────────────────────────────────────────────

	// Matches: await page.GotoAsync("url");
	private static readonly Regex GotoPattern = new(
		@"await\s+page\.GotoAsync\(\s*""([^""]*)""\s*\)",
		RegexOptions.Compiled);

	// Matches: await page.{Locator}({args}).{Action}Async({args});
	// Group 1: locator method (GetByRole, GetByText, Locator, etc.)
	// Group 2: locator args
	// Group 3: action method (Click, Fill, etc.)
	// Group 4: action args (may be empty)
	private static readonly Regex LocatorActionPattern = new(
		@"await\s+page\.(GetByRole|GetByText|GetByLabel|GetByPlaceholder|GetByTestId|GetByTitle|Locator)\((.+?)\)\.(\w+)Async\((.*?)\)\s*;",
		RegexOptions.Compiled);

	/// <summary>
	/// Translates a block of Playwright C# Library code into XUnitAssured DSL calls.
	/// Skips boilerplate lines (using statements, browser/context/page creation).
	/// </summary>
	/// <param name="playwrightCode">The raw Playwright C# code from the Inspector.</param>
	/// <param name="indent">Indentation prefix for each DSL line (default: tab + tab).</param>
	/// <returns>Translated DSL code as a string, one method call per line.</returns>
	public static string Translate(string playwrightCode, string indent = "\t\t\t")
	{
		if (string.IsNullOrWhiteSpace(playwrightCode))
			return string.Empty;

		var lines = playwrightCode.Split('\n');
		var result = new StringBuilder();

		foreach (var rawLine in lines)
		{
			var line = rawLine.Trim();
			if (string.IsNullOrEmpty(line)) continue;
			if (IsBoilerplate(line)) continue;

			var translated = TranslateLine(line);
			if (translated != null)
				result.AppendLine($"{indent}{translated}");
		}

		return result.ToString().TrimEnd();
	}

	/// <summary>
	/// Translates a single line of Playwright C# code into a DSL method call.
	/// Returns null if the line cannot be translated.
	/// </summary>
	public static string? TranslateLine(string line)
	{
		if (string.IsNullOrWhiteSpace(line)) return null;

		line = line.Trim();

		// GotoAsync → NavigateTo
		var gotoMatch = GotoPattern.Match(line);
		if (gotoMatch.Success)
		{
			var url = gotoMatch.Groups[1].Value;
			return $".NavigateTo(\"{url}\")";
		}

		// Locator + Action pattern
		var match = LocatorActionPattern.Match(line);
		if (match.Success)
		{
			var locatorMethod = match.Groups[1].Value;
			var locatorArgs = match.Groups[2].Value.Trim();
			var actionMethod = match.Groups[3].Value;
			var actionArgs = match.Groups[4].Value.Trim();

			return BuildDslCall(locatorMethod, locatorArgs, actionMethod, actionArgs);
		}

		// Unrecognized line — return as comment
		return $"// TODO: {line}";
	}

	// ──────────────────────────────────────────────
	// Internal: build the DSL method call
	// ──────────────────────────────────────────────

	private static string? BuildDslCall(string locatorMethod, string locatorArgs, string actionMethod, string actionArgs)
	{
		// Resolve the DSL action prefix (Click, Fill, DoubleClick, etc.)
		if (!ActionMap.TryGetValue(actionMethod, out var dslAction))
			return $"// TODO (unsupported action '{actionMethod}'): page.{locatorMethod}({locatorArgs}).{actionMethod}Async({actionArgs})";

		// Resolve the DSL locator suffix (ByRole, ByText, ByLabel, etc.)
		if (!LocatorSuffixMap.TryGetValue(locatorMethod, out var dslSuffix))
			return $"// TODO (unsupported locator '{locatorMethod}'): page.{locatorMethod}({locatorArgs}).{actionMethod}Async({actionArgs})";

		var methodName = $"{dslAction}{dslSuffix}";
		var parameters = BuildParameters(locatorMethod, locatorArgs, actionMethod, actionArgs);

		return $".{methodName}({parameters})";
	}

	private static string BuildParameters(string locatorMethod, string locatorArgs, string actionMethod, string actionArgs)
	{
		var parts = new List<string>();

		switch (locatorMethod)
		{
			case "GetByRole":
				ParseRoleArgs(locatorArgs, parts);
				break;

			case "GetByText":
			case "GetByLabel":
			case "GetByPlaceholder":
			case "GetByTitle":
				ParseTextArgs(locatorArgs, parts);
				break;

			case "GetByTestId":
				parts.Add(ExtractQuotedString(locatorArgs));
				break;

			case "Locator":
				parts.Add(ExtractQuotedString(locatorArgs));
				break;
		}

		// Add action value if present (Fill, Press, SelectOption, TypeText, UploadFile)
		if (!string.IsNullOrEmpty(actionArgs))
		{
			var actionValue = ExtractQuotedString(actionArgs);
			parts.Add(actionValue);
		}

		return string.Join(", ", parts);
	}

	// ──────────────────────────────────────────────
	// Argument parsers
	// ──────────────────────────────────────────────

	/// <summary>
	/// Parses GetByRole args like: AriaRole.Button, new() { Name = "Click me" }
	/// </summary>
	private static void ParseRoleArgs(string args, List<string> parts)
	{
		// Extract AriaRole.X
		var roleMatch = Regex.Match(args, @"AriaRole\.(\w+)");
		if (roleMatch.Success)
		{
			parts.Add($"AriaRole.{roleMatch.Groups[1].Value}");
		}

		// Extract Name = "value" from new() { Name = "value" }
		var nameMatch = Regex.Match(args, @"Name\s*=\s*""([^""]*)""");
		if (nameMatch.Success)
		{
			parts.Add($"\"{nameMatch.Groups[1].Value}\"");
		}
	}

	/// <summary>
	/// Parses GetByText/GetByLabel/GetByPlaceholder/GetByTitle args like:
	/// "text" or "text", new() { Exact = true }
	/// </summary>
	private static void ParseTextArgs(string args, List<string> parts)
	{
		// Extract the text value
		var textMatch = Regex.Match(args, @"""([^""]*)""");
		if (textMatch.Success)
		{
			parts.Add($"\"{textMatch.Groups[1].Value}\"");
		}

		// Check for Exact = true
		var exactMatch = Regex.Match(args, @"Exact\s*=\s*(true|false)", RegexOptions.IgnoreCase);
		if (exactMatch.Success && exactMatch.Groups[1].Value.Equals("true", StringComparison.OrdinalIgnoreCase))
		{
			// For actions that have a value param (Fill, Press), exact goes after the value
			// For now, we add it — the caller will adjust parameter order
		}
	}

	/// <summary>
	/// Extracts the first quoted string from an argument string.
	/// </summary>
	private static string ExtractQuotedString(string args)
	{
		var match = Regex.Match(args, @"""([^""]*)""");
		return match.Success ? $"\"{match.Groups[1].Value}\"" : args.Trim();
	}

	// ──────────────────────────────────────────────
	// Boilerplate detection
	// ──────────────────────────────────────────────

	private static bool IsBoilerplate(string line)
	{
		// Exact match for standalone brace lines
		if (BoilerplateExactLines.Contains(line))
			return true;

		// StartsWith match for boilerplate prefixes
		foreach (var pattern in BoilerplateStartPatterns)
		{
			if (line.StartsWith(pattern, StringComparison.OrdinalIgnoreCase))
				return true;
		}
		return false;
	}

	// ──────────────────────────────────────────────
	// Pretty-print for console output
	// ──────────────────────────────────────────────

	/// <summary>
	/// Translates Playwright code and formats it as a complete Given() block for console output.
	/// </summary>
	public static string TranslateToGivenBlock(string playwrightCode)
	{
		var translated = Translate(playwrightCode, indent: "\t\t\t");
		if (string.IsNullOrWhiteSpace(translated))
			return "// No translatable Playwright actions found.";

		var sb = new StringBuilder();
		sb.AppendLine("\tGiven()");
		sb.Append(translated);
		sb.AppendLine();
		sb.AppendLine("\t.When()");
		sb.AppendLine("\t\t.Execute()");
		sb.AppendLine("\t.Then()");
		sb.AppendLine("\t\t.AssertSuccess();");

		return sb.ToString();
	}
}
